### ISSUE TITLE
ReferenceError: Twilio is not defined Error while logging in as an agent

### ISSUE THREAD

**Issue by FishTheOriginal** [nash-md/twilio-contact-center#21]
After I go through the setup page and add an agent.

I try to login as the agent I created, I get this error:

```
2018-10-25T23:12:21.130800+00:00 app[web.1]: ReferenceError: Twilio is not defined
2018-10-25T23:12:21.130818+00:00 app[web.1]:     at Object.module.exports.createWorkerCapabilityToken (/app/controllers/helpers/taskrouter-helper.js:71:30)
2018-10-25T23:12:21.130820+00:00 app[web.1]:     at createWorkerTokens (/app/controllers/agents.js:54:44)
2018-10-25T23:12:21.130821+00:00 app[web.1]:     at client.taskrouter.workspaces.workers.list.then.workers (/app/controllers/agents.js:25:20)
2018-10-25T23:12:21.130823+00:00 app[web.1]:     at Promise_then_fulfilled (/app/node_modules/q/q.js:766:44)
2018-10-25T23:12:21.130824+00:00 app[web.1]:     at Promise_done_fulfilled (/app/node_modules/q/q.js:835:31)
2018-10-25T23:12:21.130826+00:00 app[web.1]:     at Fulfilled_dispatch [as dispatch] (/app/node_modules/q/q.js:1229:9)
2018-10-25T23:12:21.130827+00:00 app[web.1]:     at Pending_become_eachMessage_task (/app/node_modules/q/q.js:1369:30)
2018-10-25T23:12:21.130829+00:00 app[web.1]:     at RawTask.call (/app/node_modules/asap/asap.js:40:19)
2018-10-25T23:12:21.130830+00:00 app[web.1]:     at flush (/app/node_modules/asap/raw.js:50:29)
2018-10-25T23:12:21.130832+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
```

**Comment by nash-md** [comment]
Fixed with 0cdbc36488a257152c956ae831cf44dcad443b32
