### ISSUE TITLE
error after set up SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by DMKITServices** [nash-md/twilio-contact-center#22]
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/twilio-contact-center/app.js:14:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by nash-md** [comment]
This issue is fixed.
