### ISSUE TITLE
Error: The requested resource /Services/undefined was not found

### ISSUE THREAD

**Issue by carlbateson** [nash-md/twilio-contact-center#31]
When trying to save the configuration from https://xxx.ngrok.io/setup/ or http://localhost:5000/setup, I'm getting this error:

```
{"stack": "Error: The requested resource /Services/undefined was not found
 at success (/Users/.../src/twilio-contact-center/node_modules/twilio/lib/base/Version.js:88:15)
 at Promise_then_fulfilled (/Users/.../twilio-contact-center/node_modules/q/q.js:766:44)
 at Promise_done_fulfilled (/Users/.../twilio-contact-center/node_modules/q/q.js:835:31)
 at Fulfilled_dispatch [as dispatch] (/Users/.../twilio-contact-center/node_modules/q/q.js:1229:9)
 at Pending_become_eachMessage_task (/Users/.../twilio-contact-center/node_modules/q/q.js:1369:30)
 at RawTask.call (/Users/.../twilio-contact-center/node_modules/asap/asap.js:40:19)
 at flush (/Users/.../twilio-contact-center/node_modules/asap/raw.js:50:29)
 at processTicksAndRejections (internal/process/task_queues.js:79:11)", "message": "The requested resource /Services/undefined was not found", "status": 404, "code": 20404, "moreInfo": "https://www.twilio.com/docs/errors/20404" }
```

(Note, my absolute file path has been masked)

**Comment by nash-md** [comment]
Can you please check if **process.env.TWILIO_CHAT_SERVICE_SID** was set on your installation?
