### ISSUE TITLE
One click install not working

### ISSUE THREAD

**Issue by ZeroCoolHacker** [nash-md/twilio-contact-center#35]
First of all thank you for creating this app.
I am trying to run the one click install but it gives me this error

`bash
021-06-04T20:11:01.030011+00:00 app[web.1]: at Connection.parseE (/app/node_modules/pg/lib/connection.js:614:13)
2021-06-04T20:11:01.030012+00:00 app[web.1]: at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:413:19)
2021-06-04T20:11:01.030012+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:129:22)
2021-06-04T20:11:01.030013+00:00 app[web.1]: at Socket.emit (events.js:198:13)
2021-06-04T20:11:01.030013+00:00 app[web.1]: at addChunk (_stream_readable.js:288:12)
2021-06-04T20:11:01.030014+00:00 app[web.1]: at readableAddChunk (_stream_readable.js:269:11)
2021-06-04T20:11:01.030015+00:00 app[web.1]: at Socket.Readable.push (_stream_readable.js:224:10)
2021-06-04T20:11:01.030015+00:00 app[web.1]: at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
2021-06-04T20:11:01.030016+00:00 app[web.1]: name: 'error',
2021-06-04T20:11:01.030017+00:00 app[web.1]: length: 166,
2021-06-04T20:11:01.030017+00:00 app[web.1]: severity: 'FATAL',
2021-06-04T20:11:01.030017+00:00 app[web.1]: code: '28000',
2021-06-04T20:11:01.030018+00:00 app[web.1]: detail: undefined,
2021-06-04T20:11:01.030018+00:00 app[web.1]: hint: undefined,
2021-06-04T20:11:01.030018+00:00 app[web.1]: position: undefined,
2021-06-04T20:11:01.030019+00:00 app[web.1]: internalPosition: undefined,
2021-06-04T20:11:01.030019+00:00 app[web.1]: internalQuery: undefined,
2021-06-04T20:11:01.030020+00:00 app[web.1]: where: undefined,
2021-06-04T20:11:01.030020+00:00 app[web.1]: schema: undefined,
2021-06-04T20:11:01.030020+00:00 app[web.1]: table: undefined,
2021-06-04T20:11:01.030021+00:00 app[web.1]: column: undefined,
2021-06-04T20:11:01.030021+00:00 app[web.1]: dataType: undefined,
2021-06-04T20:11:01.030021+00:00 app[web.1]: constraint: undefined,
2021-06-04T20:11:01.030022+00:00 app[web.1]: file: 'auth.c',
2021-06-04T20:11:01.030022+00:00 app[web.1]: line: '496',
2021-06-04T20:11:01.030022+00:00 app[web.1]: routine: 'ClientAuthentication' }
2021-06-04T20:11:01.037478+00:00 app[web.1]: { error: no pg_hba.conf entry for host "3.82.155.179", user "yiopqnaotjiegs", database "d9cjggvojcen42", SSL off
`

**Comment by nash-md** [comment]
Please check the error message in your ticket **error: no pg_hba.conf entry for host "3.82.155.179",  ... ** , NodeJS is unable to connect to your database

**Comment by ZeroCoolHacker** [comment]
Had to buy it for some unknown reason.

**Comment by theviktor** [comment]
@ZeroCoolHacker how did u get this working?, what did u have to buy?

**Comment by ZeroCoolHacker** [comment]
> @ZeroCoolHacker how did u get this working?, what did u have to buy?

Well i am using ngrok to get a public url. dont have to go through heroku errors.
But twilio bans your account if you don't provide them enough information.
