### ISSUE TITLE
The application could not access the TwiML Application.

### ISSUE THREAD

**Issue by CodeTerminator007** [nash-md/twilio-contact-center#37]
The application could not access the TwiML Application. and also getting the error on setup page 

Oh snap!
{ "stack": "Error: The requested resource /2010-04-01/Accounts/AC65baeed0743da28a3fb1c82bab432e0b/Applications/AP183378e0911ec8d9549015e0bd96bab4.json was not found\n at success (E:\\Contact-Center\\twilio-contact-center\\node_modules\\twilio\\lib\\base\\Version.js:88:15)\n at Promise_then_fulfilled (E:\\Contact-Center\\twilio-contact-center\\node_modules\\q\\q.js:766:44)\n at Promise_done_fulfilled (E:\\Contact-Center\\twilio-contact-center\\node_modules\\q\\q.js:835:31)\n at Fulfilled_dispatch [as dispatch] (E:\\Contact-Center\\twilio-contact-center\\node_modules\\q\\q.js:1229:9)\n at Pending_become_eachMessage_task (E:\\Contact-Center\\twilio-contact-center\\node_modules\\q\\q.js:1369:30)\n at RawTask.call (E:\\Contact-Center\\twilio-contact-center\\node_modules\\asap\\asap.js:40:19)\n at flush (E:\\Contact-Center\\twilio-contact-center\\node_modules\\asap\\raw.js:50:29)\n at processTicksAndRejections (internal/process/task_queues.js:79:11)", "message": "The requested resource /2010-04-01/Accounts/AC65baeed0743da28a3fb1c82bab432e0b/Applications/AP183378e0911ec8d9549015e0bd96bab4.json was not found", "status": 404, "code": 20404, "moreInfo": "https://www.twilio.com/docs/errors/20404" }

waiting  for your reply

**Comment by CodeTerminator007** [comment]
Mb I fixed it
