### ISSUE TITLE
Error: keySid is required

### ISSUE THREAD

**Issue by brettev** [nash-md/twilio-contact-center#4]
I got through the install, got the success on the /setup screen. Went to log in as an agent, and got this error:

Error: keySid is required
    at new AccessToken (/var/www/twilio-contact-center/node_modules/twilio/lib/AccessToken.js:73:24)
    at /var/www/twilio-contact-center/controllers/agents.js:55:23
    at /var/www/twilio-contact-center/node_modules/twilio/node_modules/q/q.js:1920:17
    at flush (/var/www/twilio-contact-center/node_modules/twilio/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)

Is this because of a node module update? 

I'm not using the IP Messaging piece, so I don't have those env vars set. Not sure if that matters.

**Comment by brettev** [comment]
Looks like the IP Messaging Keys are required even if you aren't planning on using them. I'll close this out :)
